name: phoenix_wings
description: Phoenix Channel client for Dart
version: 0.0.2
author: mfeckie<mfeckie@gmail.com>
homepage: https://github.com/mfeckie/phoenix_wings

dev_dependencies:
  dartdoc: "^0.15.0+1"
  test: "^0.12.29+1"
  mockito: "^2.2.1"
  stream_channel: "^1.6.4"
