name: phoenix_wings
description: Phoenix Channel client for Dart
version: 0.0.1
author: mfeckie<mfeckie@gmail.com>
homepage: https://github.com/mfeckie/phoenix_wings

dependencies:

dev_dependencies:
  dartdoc: "^0.15.0+1"
  test: "^0.12.29+1"
  mockito: "^2.2.1"
