name: phoenix_wings
description: Phoenix Channel client for Dart
version: 0.1.2
author: mfeckie<mfeckie@gmail.com>
homepage: https://github.com/mfeckie/phoenix_wings

dev_dependencies:
  flutter:
    sdk: flutter
  dartdoc: "0.24.1"
  test: "1.3.4"
  mockito: "^3.0.0"
  stream_channel: "^1.6.4"
  intl: "^0.15.6"

environment:
  sdk: '>=1.2.3 <3.0.0'